variables:
  TEST_VAR: "Azazaza"

stages: 
  - build

build-web: 
  stage: build
  script: 
    - docker --version
  tags:
    - docker

job1:
  stage: build
  variables:
    TEST_VAR_JOB: "Only job1 can use this variable's value"
  script:
    - echo "$TEST_VAR" and "$TEST_VAR_JOB" "$CI_PROJECT_NAME"