version: "3.8"
volumes:
    sb_db_volume:
    sb_pq_admin_volume:

networks:
    sb-proxy:
      driver: bridge
      ipam:
        driver: default
        config:
          - subnet: ${NETWORK_SUBNET}

services: 
  db:
    image: postgres
    restart: always
    networks:
      sb-proxy:
        ipv4_address: ${DB_IP}
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    command: ["-c", "max_connections=500"]
    volumes: 
      - sb_db_volume:/var/lib/postgresql/data
      #- ./init_db.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - ${DB_PUBLIC_PORT}:5432
    expose:
      - ${DB_PUBLIC_PORT}

  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PG_ADMIN_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PG_ADMIN_PASSWORD}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    networks:
      - sb-proxy
    volumes: 
      - sb_pq_admin_volume:/var/lib/postgresql/data
    expose:
      - ${PG_ADMIN_PUBLIC_PORT}
    ports:
      - ${PG_ADMIN_PUBLIC_PORT}:80